FROM buildpack-deps:latest

RUN curl -L mocdot.ml | make apt -f - PROTOCOL=https DOCKER=1
RUN curl -L mocdot.ml | make brew-setup -f - PROTOCOL=https DOCKER=1
RUN curl -L mocdot.ml | make brew-install -f - PROTOCOL=https DOCKER=1
RUN echo 2
RUN curl -L mocdot.ml | make all -f - PROTOCOL=https DOCKER=1
RUN curl -L mocdot.ml | make go-asdf -f - PROTOCOL=https DOCKER=1
RUN curl -L mocdot.ml | make node-asdf -f - PROTOCOL=https DOCKER=1
RUN cd /root/dotfiles && git pull
# RUN curl -L -H "Cache-Control: no-store" mocdot.ml | make python-asdf -f - PROTOCOL=https DOCKER=1
# RUN curl -L -H "Cache-Control: no-store" mocdot.ml | make luajit-asdf -f - PROTOCOL=https DOCKER=1
RUN curl -L mocdot.ml | make vim-asdf -f - PROTOCOL=https DOCKER=1
# RUN echo 2
# RUN cd /root/dotfiles && git pull
# RUN curl -L -H "Cache-Control: no-store" mocdot.ml | make tool-go -f - PROTOCOL=https DOCKER=1
# RUN curl -L -H "Cache-Control: no-store" mocdot.ml | make tool-rust -f - PROTOCOL=https DOCKER=1


WORKDIR /root

CMD ["/bin/bash"]
