# Local Path
# TODO: パスの指定を zsh らしくする
if [ -d $HOME/.local/bin ]; then
    export PATH=$HOME/.local/bin:$PATH
fi

# Homebrew (Linux)
if [ $(uname) = "Linux" ]; then
    if [ -d ~/.linuxbrew ]; then
      eval $(~/.linuxbrew/bin/brew shellenv)
    fi
    if [ -d /home/linuxbrew/.linuxbrew ]; then
      eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
    fi
    if [ -r ~/.bash_profile ]; then
      eval $($(brew --prefix)/bin/brew shellenv)
    fi
    eval $($(brew --prefix)/bin/brew shellenv)
fi

# Asdf
if [ -d $HOME/.asdf ]; then
    . $HOME/.asdf/asdf.sh
    # NOTE: completion がないと怒る
    # . $HOME/.asdf/completions/asdf.bash
fi


# Language Setup
## Go
if [ -d $HOME/go/bin ]; then
    export PATH=$HOME/go/bin:$PATH
fi

## Rust
if [ -d $HOME/.cargo/bin ]; then
    . "$HOME/.cargo/env"
fi

## LaTeX
if [ -d /Library/TeX/texbin ]; then
    export PATH=/Library/TeX/texbin:$PATH
fi

# Utility Setup

## Nextword
export NEXTWORD_DATA_PATH=$HOME'/.local/share/nextword-data-large'


# Zplug
source ~/.zplug/init.zsh

autoload -U promptinit; promptinit
zplug "mafredri/zsh-async"
zplug "sindresorhus/pure"

zplug load


# Keys
autoload -U up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^P" up-line-or-beginning-search
bindkey "^N" down-line-or-beginning-search

alias ls='ls -G'
alias ll='ls -l'
alias la='ls -la'
alias d-c='docker-compose'


# Options
setopt auto_cd
setopt share_history


# Env
export EDITOR=vim
